#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4
permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
