#!/usr/bin/env bash
# Bash scritp to manage the file manage_my_process.

file=/var/run/my_process.pid
case $1 in
	"start")
		./manage_my_process &
		echo $! > "$file"
		echo 'manage_my_process started'
		;;
	"restart")
		id=$(cat $file)
		kill -s SIGSTOP "$id"
		rm "$file"
		./manage_my_process &
		echo $! > "$file"
		echo 'manage_my_process restarted'
		;;
	"stop")
		id=$(cat $file)
		kill -s SIGSTOP "$id"
		rm "$file"
		echo 'manage_my_process stopped'
		;;
	*)
		echo 'Usage: manage_my_process {start|stop|restart}'
		;;
esac
