#!/usr/bin/env bash
# This script that displays:
# The content of the current directorye
# In a list format
# Where onlye the part of the name after the first dash
# is displayed

for i in *; do
    echo "$i" | cut -d'-' -f2
done
