#!/usr/bin/env bash
# Block all incoming traffic but no 22, 443 and 80

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable -y
