#!/usr/bin/env bash
# Fixes container same as task 1 with <= 7 lines of code

sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart