#!/usr/bin/env bash
# Write a Bash script that creates an RSA key pair.
# Name of the created private key must be school (-f)
# Number of bits in the created key to be created 4096 (-b)
# The created key must be protected by the passphrase betty (-N)

ssh-keygen -f school -b 4096 -N betty
